#OPERADORES ARITMETICOS

'''
    +   SUMA
    -   RESTA
    *   MULTIPLICACION
    /   DIVISION
    //  DIVISION QUE REDONDEA A NUMEROS ENTEROS
    %   MODULO (RESIDUO)
    **  POTENCIA

    DE ACUERDO A LA TABLA DE PRIORIDAD DE LOS SIMBOLOS TENEMOS QUE LAS OPERACIONES SE
    REALIZAN CON BASE AL SIGUIENTE ORDEN:

        - PARENTESIS        ()
        - EXPONENCIACION    **
        - MULTIPLICACION, DIVISION, MODULO
        - SUMA, RESTA
'''

resultado = 3 ** 3 * (13/5 - (2*4))

print(resultado)