#FUNCIONES INTEGRADAS ADEMAS DE INT, FLOAT, DOUBLE, ETCETERA

a = str(10.99)  #PARA CONVERTIR A CADENA
print(a)

b = bin(40)     #PARA CONVERTIR A BINARIO
print(b)

c = hex(82)     #PARA CONVERTIR A HEXADECIMAL
print(c)

d = int(0b1010) #PARA ESCRIBIR BINARIO SE PUEDE HACER TAMBIEN ("0b1010",2)
print(d)
#LA IDEA BASICA DE CONVERSION BINARIA ES ("0bNUMEROS",base2)

e = int(0xa)    #PARA ESCRIBIR HEXADECIMAL SE PUEDE HACER TAMBIEN ("0xa",16)
print(e)
#LA IDEA BASICA DE CONVERSION HEXADECIMAL ES ("0xNUMEROS",base16)

f = abs(-5)         #PARA CONVERTIR A VALOR ABSOLUTO
print(f)

g = round(5.85)     #PARA REDONDEAR NUMEROS
print(g)

h = len("URIEL")    #PARA LONGITUR DE CARACTERES O STRINGS
print(h)
