#CONDICIONALES
dato1 = int(input("DIGITE UN NUMERO ENTERO: "))

#LO QUE QUERAMOS METER DENTRO DEL IF, TENDRA QUE ESTAR IDENTADO
if dato1>0:
    print("EL NUMERO ES POSITIVO")
elif dato1==0:
    print("EL NUMERO ES CERO")
else:
    print("EL NUMERO ES NEGATIVO")