'''
    - SE UTILIZAN PARA ESTABLECER UNA RELACION ENTRE 2 VALORES
    - COMPARA ESTOS VALORES ENTRE SI Y ESTA COMPARACION PRODUCE
      UN RESULTADO DE CERTEZA O FALSEDAD
    - TIENE EL MISMO NIVEL DE PRIORIDAD EN SU EVALUACION
    - LOS OPERADORES RELACIONALES TIENEN MENOR PRIORIDAD QUE LOS ARITMETICOS

    >   MAYOR QUE
    <   MENOR QUE
    >=  MAYOR O IGUAL QUE
    <=  MENOR O IGUAL QUE
    !=  DIFERENTE
    ==  IGUAL
'''
resultado = 10 == 20

print(resultado)